version: "3.8"

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    volumes:
      - ./auth-service:/app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/auth

  document-service:
    build:
      context: ./document-service
    container_name: document-service
    volumes:
      - ./document-service:/app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/documents

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
