services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    volumes:
      - ./auth-service:/app
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/auth

  document-service:
    build:
      context: ./document-service
    container_name: document-service
    ports:
      - "5002:5002"
    volumes:
      - ./document-service:/app
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGO_URI=mongodb://host.docker.internal:27017/documents
      - AUTH_SERVICE_URL=http://auth-service:5001
    depends_on:
      - auth-service


  signature-service:
    build:
      context: ./signature-service
    container_name: signature-service
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
      - PORT=5003
      - MONGO_URI=mongodb://host.docker.internal:27017/signature
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - rabbitmq_data

  certificate-service:
    build: .
    container_name: certificate-service
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/certificates
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    
      - "15672:15672"   
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  redis_data:
  mongo_data:
  rabbitmq_data:
  minio-data:

