apiVersion: apps/v1
kind: Deployment
metadata:
  name: signature-service
  value: http://signature-service:5003
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signature-service
  template:
    metadata:
      labels:
        app: signature-service
    spec:
      containers:
        - name: signature-service
          image: signature-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/signature"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: signature-service
spec:
  selector:
    app: signature-service
  ports:
    - port: 5003
      targetPort: 5003
